# Generated by Django 6.0.1 on 2026-01-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_view', 'Can view article'), ('can_create', 'Can create article'), ('can_edit', 'Can edit article'), ('can_delete', 'Can delete article'), ('can_publish', 'Can publish article')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
                'permissions': [('can_view', 'Can view comment'), ('can_create', 'Can create comment'), ('can_edit', 'Can edit comment'), ('can_delete', 'Can delete comment')],
            },
        ),
    ]
